# Generated by Django 3.2.5 on 2021-07-15 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bills',
            fields=[
                ('billID', models.IntegerField(primary_key=True, serialize=False)),
                ('billDate', models.DateField()),
                ('dueDate', models.DateField()),
                ('charge', models.DecimalField(decimal_places=2, max_digits=65)),
                ('anc_fees', models.DecimalField(decimal_places=2, max_digits=65)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=65)),
                ('credit', models.DecimalField(decimal_places=2, max_digits=65)),
            ],
        ),
        migrations.CreateModel(
            name='Carriers',
            fields=[
                ('carrierId', models.IntegerField(primary_key=True, serialize=False)),
                ('carrierName', models.CharField(max_length=40)),
                ('carrierAcctNum', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('prodID', models.IntegerField(primary_key=True, serialize=False)),
                ('product', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='BillsPaid',
            fields=[
                ('paidID', models.IntegerField(primary_key=True, serialize=False)),
                ('paidDate', models.DateField()),
                ('notes', models.CharField(max_length=100)),
                ('paidBool', models.BooleanField()),
                ('totalPaid', models.DecimalField(decimal_places=2, max_digits=65)),
                ('billID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.bills', verbose_name='related bill')),
            ],
        ),
        migrations.AddField(
            model_name='bills',
            name='carrierID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.carriers', verbose_name='related carrier'),
        ),
        migrations.AddField(
            model_name='bills',
            name='prodID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bills.products', verbose_name='related product'),
        ),
    ]
