# Generated by Django 3.2.5 on 2021-08-04 19:01

import bills.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='billID',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
        migrations.AlterField(
            model_name='billpaid',
            name='paidID',
            field=models.IntegerField(default=bills.models.BillPaid.id_default, editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Paid ID'),
        ),
        migrations.AlterField(
            model_name='carrier',
            name='carrierId',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Carrier ID'),
        ),
        migrations.AlterField(
            model_name='monthlybreakdown',
            name='mbdID',
            field=models.IntegerField(default=bills.models.MonthlyBreakdown.id_default, editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Monthly Billed ID'),
        ),
        migrations.AlterField(
            model_name='product',
            name='prodID',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
