# Generated by Django 3.2.5 on 2021-08-04 19:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0002_auto_20210804_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpaid',
            name='paidID',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10000)], verbose_name='Paid ID'),
        ),
    ]
