# Generated by Django 3.2.5 on 2021-08-11 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0004_alter_billpaid_paiddate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpaid',
            name='paidDate',
            field=models.DateField(blank=True, null=True, verbose_name='Date Paid'),
        ),
    ]
