# Generated by Django 3.2.5 on 2021-08-31 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bills', '0006_alter_product_prodid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrier',
            name='carrierId',
            field=models.AutoField(editable=False, primary_key=True, serialize=False),
        ),
    ]
